language: go
script: go run main.go & sleep 1 && go test && export TESTS_PASSED=yes;
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jdeklerk
  password:
    secure: ZG8VUW7AsbGZmS9IsJnduO6nPt2NvZ+fGZXnGstkINwb4tNL+1sEAeUmn856IoBgJMef0DoC2po+bcHkdcFhhDhLGM6bloVP0zEF/uXr02BIH/GDtqpyKL9SkYCWGLvbGm4dBQutnmkyyswrGHipZciaATKC+F9mfeUWN4QQHJwb9p6E0YdLELHrGXD6TlCpd7dUidH7fFKJ74fKVwSxQuXBmWNv/1EoRk223ohOnmsekCF6o5To6YEmTfpLOXFsHRtr6Pa0dOjV4Mi3JSHDNqZcoVTqDJaiBrGfNeV5YoS3QLjydnVUv3AanktfJLrxrnJTOIy3wKxXJUG/JaFQUxBYRjEjb6y++HcJAd7DNTogT5PMmrM92yrwHoV4zIXZ2ytM0I3vTmRdssSCIMeYiBfLHUVAioF9G2R9tkqKd2wQ4ID2e819imdrcjth1DCY+5dyEDvmDiKwj42ncHmR7AkUUffFfwmMrpKIenjemYDu7TElWCXVJErHDz+RqKvFS7qGo3TVyZyabvvaEYY87Ubhlz+cOjJ0F/uqvCEG+muNwjXN8OOWpKhF/TrJcyE2AyzddtcEUbmHUkZRuK3NcTpeJYf7ndsV5iI5LTUxKJQB5Fj6JWM8ngcb0yQaeQ+fpMTNg3K1YN1YuWv5QrvnnMVmARBt6IqLfcWNRbz0UT0=
  organization: denver-labs
  space: development
  on:
    repo: jadekler/git-cicd-talk
