language: go
script:
  go run main.go &
  sleep 1 &&
  go test &&
  export TESTS_PASSED=yes;
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jdeklerk@pivotal.io
  password:
    secure: gecb6P34q4V1kuLQ5ySGWrpklSOS//ZcOh3N063g6QRl6IkBzpw70voUymnylO3CwEog7aTV5WaqPzclFuVR+eBAjROAsGIWKBLNUiwmF/2B3UNC2UqJS9wkV34yjJTj16qBaUyA5NsTAHhqfOWgqOpAQMA+6l8EUL5d4ll+I2WQ7UfQP+nfnjRXziHl8RnrdJ8QpuSLR5YHUYs/InjdpdSmOAMTdwtZAw/pm3iHX5H3mqE06KOmDGOXTAGWKjAYPZWSKvYQ6Su/dLCGiEfbZQwfY05k0TsTB5dlFThlisxGzsQU8IM9kpu27b+iY/xfI+JePbTvJ39ddAeJ5NNsW9C8a2djCry1QDASfSw429TbJm0ozPfqC3atzItAP69lV3jerZCZf6Yiw0aMcCOaJIT6vkn2vxHCY9B0opDs965hQ7T4leRn9ZpDD8ywDnbOL7xJrPXTk95mMYjPJNnrYmXhacK5RI/wdNmGt+Vv9NBr5n/1Uq7ttgkYszA+Eb9g8aG4ahUT1c8sNJuy9fp4MjrfrE9OriA/1paEX1WU47wPYsmX8h8JYSsJ8jYwVz2mmQyL0NIx4Lk0TAnpF9jgY+f2fP950Xk5uGj6HjcjpWwb1PI6iE+LqJNLnMc62uci+YKuv3vtvDdJfcyQhqB0LD3VKrzceyAuNdyRhoJWKoo=
  organization: denver-labs
  space: development
  on:
    repo: jadekler/git-cicd-talk
    condition: $TESTS_PASSED = yes
